RACDOOR = ../..

BIN = csvmerge
SRCS = csvmerge.c

host: csvmerge
ee:
clean: compileclean linkclean

include $(RACDOOR)/make/config.$(TARGET).mk
include $(RACDOOR)/make/compile.mk
include $(RACDOOR)/make/link.$(TARGET).mk
