PROJECTDIR = ../..

BIN = csvmerge
SRCS = csvmerge.c

host: csvmerge
ee:
clean: compileclean linkclean

include $(PROJECTDIR)/make/config.$(TARGET).mk
include $(PROJECTDIR)/make/compile.mk
include $(PROJECTDIR)/make/link.$(TARGET).mk
