PROJECTDIR = ..

BIN = racdoor
SRCS = racdoor.c

host: racdoor
ee:
clean: compileclean linkclean

include $(PROJECTDIR)/make/config_$(TARGET).mk
include $(PROJECTDIR)/make/compile.mk
include $(PROJECTDIR)/make/link_$(TARGET).mk
