PROJECTDIR = ..

BIN = tblgen
SRCS = tblgen.c

host: tblgen
ee:
clean: compileclean linkclean

include $(PROJECTDIR)/make/config_$(TARGET).mk
include $(PROJECTDIR)/make/compile.mk
include $(PROJECTDIR)/make/link_$(TARGET).mk
