@node Overview
@chapter Overview

Racdoor is the product of over 500 years of development at the Galactic Security
Agency (GSA) in service of the Galactic Security mission and represents the most
significant advance in strategic cyber capabilities in recorded history.

It allows for a covert implant to be injected into a Ratchet & Clank (PS2) save
game such that the payload code embedded in the file is executed on the victim
console shortly after the file is loaded by the game.

@noindent
@b{Features:}

@itemize

@item
Achieves persistence by injecting itself into save games created while it is
installed.

@item
Survives level transitions by using a flexible custom dynamic linking system.

@item
Next generation stealth via military grade encryption.

@item
Payload compression leveraging the game's own internal LZ decoder.

@item
Function entry point and call hooking capabilities.

@end itemize

@noindent
@b{Status:}
Released.

@noindent
@b{Unit Cost:}
100,000,000 bolts
@footnote{By cloning the Git repository or otherwise downloading its contents
you hereby agree to send me the amount in full within two weeks.}
