PROJECTDIR = ..

BIN = addrgen
SRCS = addrgen.c

host: addrgen
ee:
clean: compileclean linkclean

include $(PROJECTDIR)/make/config_$(TARGET).mk
include $(PROJECTDIR)/make/compile.mk
include $(PROJECTDIR)/make/link_$(TARGET).mk
